namespace Warp.Core.Metrics;

/// <summary>Time resolution of a metric series, mirroring the storage tiers (§8.30). Values start at 1 (§8.11).</summary>
public enum MetricResolution
{
    /// <summary>Fine (5-minute) buckets.</summary>
    Fine = 1,

    /// <summary>Hourly buckets.</summary>
    Hourly = 2,

    /// <summary>Daily buckets.</summary>
    Daily = 3,
}

/// <summary>How a series bucket combines the samples that fall in it. Values start at 1 (§8.11).</summary>
public enum MetricAggregation
{
    /// <summary>Sum the samples (counters / sums).</summary>
    Sum = 1,

    /// <summary>Take the latest sample (gauges).</summary>
    Last = 2,
}

/// <summary>A half-open UTC window <c>[FromUtc, ToUtc)</c> for a metric query.</summary>
public readonly record struct MetricWindow(DateTime FromUtc, DateTime ToUtc);

/// <summary>
/// A logical reference to one of Warp's own metrics: a <paramref name="Name"/> plus an optional exact-match
/// <paramref name="Tags"/> filter. Deliberately backend-neutral — it is NOT a storage key. The local backend maps
/// it to the colon-delimited <c>Statistic</c>/<c>Counter</c> keys (§8.6/§8.19); a Prometheus backend maps it to a
/// metric name + label matchers (<c>name{tag="v"}</c>). Because Warp only ever references its own known metrics,
/// the backend generates the query — there is no user-facing query language.
/// </summary>
public sealed record MetricRef(string Name, IReadOnlyDictionary<string, string>? Tags = null);

/// <summary>
/// A windowed, bucketed series query, optionally split by one tag. Local backend → a merged Statistic+Counter read
/// grouped by tier bucket (down-binned to <see cref="Resolution"/>); Prometheus backend →
/// <c>sum by (BreakdownBy)(increase(name{tags}[step]))</c> over the range.
/// </summary>
public sealed record SeriesQuery(
    MetricRef Metric,
    MetricWindow Window,
    MetricResolution Resolution,
    MetricAggregation Aggregation,
    string? BreakdownBy = null);

/// <summary>One point of a series. <paramref name="TagValue"/> is the split value when the query set <c>BreakdownBy</c>, else null.</summary>
public sealed record SeriesBucket(DateTime BucketStart, string? TagValue, long Value);

/// <summary>
/// The read seam for Warp's own metrics (§8.3x). Every dashboard / SLO-evaluator metric read reduces to these four
/// operations, so the backing store is pluggable: the default <c>LocalMetricSource</c> reads the durable
/// <c>Statistic</c>/<c>Counter</c> fold; a later backend can read the same metrics back from an external TSDB
/// (Prometheus) that Warp exported to via OTel. The data is always Warp's own, known-shape metrics — so the queries
/// are generated by the backend, never authored by a user (no graph editor, not federation of arbitrary series).
/// Read-side only, off the worker hot path (§0.2/§6.1).
/// </summary>
public interface IMetricSource
{
    /// <summary>Total for a metric — lifetime when <paramref name="window"/> is null, else summed over the window. Local → combined Statistic+Counter for the key; Prometheus → an instant/range sum.</summary>
    Task<long> GetTotalAsync(MetricRef metric, MetricWindow? window, CancellationToken ct);

    /// <summary>A bucketed series over a window, optionally split by one tag (see <see cref="SeriesQuery"/>).</summary>
    Task<IReadOnlyList<SeriesBucket>> GetSeriesAsync(SeriesQuery query, CancellationToken ct);

    /// <summary>The <paramref name="percentile"/> (e.g. 95) of a latency histogram metric over the window. Local → percentile walk over the tiered <c>pcth</c> buckets; Prometheus → <c>histogram_quantile</c>.</summary>
    Task<double> GetPercentileAsync(MetricRef metric, int percentile, MetricWindow window, CancellationToken ct);

    /// <summary>The current value of a gauge metric, or null when it has never been reported. Local → the latest <c>Statistic</c> value; Prometheus → an instant query.</summary>
    Task<double?> GetGaugeAsync(MetricRef metric, CancellationToken ct);
}
