<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>07874f0e-e5e8-4140-96f4-3d6c3e389cf9</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Warp.Core\Warp.Core.csproj" />
    <ProjectReference Include="..\..\core\Warp.Http\Warp.Http.csproj" />
    <ProjectReference Include="..\..\core\Warp.UI\Warp.UI.csproj" />
    <ProjectReference Include="..\..\core\Warp.Worker\Warp.Worker.csproj" />
    <ProjectReference Include="..\..\core\Warp.Adapters.Http\Warp.Adapters.Http.csproj" />
    <ProjectReference Include="..\..\core\Warp.Adapters.Refit\Warp.Adapters.Refit.csproj" />
    <ProjectReference Include="..\..\core\Warp.Adapters.Webhooks\Warp.Adapters.Webhooks.csproj" />
    <ProjectReference Include="..\..\core\providers\Warp.Provider.PostgreSql\Warp.Provider.PostgreSql.csproj" />
    <ProjectReference Include="..\Warp.Demo.ServiceDefaults\Warp.Demo.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Warp.Test.Shared\Warp.Test.Shared.csproj" />
    <ProjectReference Include="..\..\core\Warp.SourceGenerator\Warp.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\core\Warp.Http.SourceGenerator\Warp.Http.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
