using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Warp.Tests.SourceGenerator;

[Generator]
public sealed class DatabaseTestsGenerator : IIncrementalGenerator
{
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Warp.Tests;

        [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        internal sealed class GenerateDatabaseTestsAttribute : System.Attribute
        {
            /// <summary>
            /// Set to true for test classes that exercise the database-push path
            /// (UseDatabasePush, SqlServerNotificationTransport). Picks the SQL Server
            /// fixture variant with Service Broker enabled. PostgreSQL's LISTEN/NOTIFY
            /// works without setup, so this only affects the SQL Server side.
            /// </summary>
            public bool WithPush { get; set; }

            /// <summary>
            /// Opt heavyweight integration classes (those that boot one or more full
            /// <c>WarpTestServer</c> hosts) into a shared, serialized xUnit collection.
            /// Classes sharing a name never run concurrently with each other, capping how
            /// many heavy servers hammer the shared test container at once — light test
            /// classes still parallelize freely. This is the load-side fix for the
            /// thread-pool/DB-pool starvation that surfaces as unrelated timing flakes
            /// (see .claude/rules/testing.md and feedback_integration_test_good_neighbor).
            /// </summary>
            public string? SerializeInCollection { get; set; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateDatabaseTestsAttribute.g.cs", AttributeSource));

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 } c
                    && c.Modifiers.Any(m => string.Equals(m.ValueText, "abstract", System.StringComparison.Ordinal)),
                transform: static (ctx, _) => GetTargetOrNull(ctx))
            .Where(static x => x is not null)!
            .Collect();

        context.RegisterSourceOutput(provider, static (spc, targets) =>
        {
            foreach (var target in targets.Distinct())
            {
                Emit(spc, target!);
            }
        });
    }

    private static Target? GetTargetOrNull(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null)
        {
            return null;
        }

        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            string.Equals(a.AttributeClass?.ToDisplayString(), "Warp.Tests.GenerateDatabaseTestsAttribute", System.StringComparison.Ordinal));
        if (attr is null)
        {
            return null;
        }

        var withPush = false;
        string? collection = null;
        foreach (var named in attr.NamedArguments)
        {
            if (string.Equals(named.Key, "WithPush", System.StringComparison.Ordinal)
                && named.Value.Value is bool b)
            {
                withPush = b;
            }

            if (string.Equals(named.Key, "SerializeInCollection", System.StringComparison.Ordinal)
                && named.Value.Value is string s)
            {
                collection = s;
            }
        }

        return new Target(
            @namespace: symbol.ContainingNamespace.ToDisplayString(),
            baseName: symbol.Name,
            withPush: withPush,
            collection: collection);
    }

    private static void Emit(SourceProductionContext spc, Target target)
    {
        var (ns, baseName, withPush, collection) = target;
        var sqlFixture = withPush ? "SqlServerPushClassFixture" : "SqlServerClassFixture";

        // Strip the Base suffix if present — produces RetryTests_PostgreSql for RetryTestsBase.
        var concreteName = baseName.EndsWith("Base", System.StringComparison.Ordinal)
            ? baseName.Substring(0, baseName.Length - 4)
            : baseName;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("[Xunit.Trait(\"Category\", \"PostgreSql\")]");
        if (collection is not null)
        {
            sb.AppendLine($"[Xunit.Collection(\"{collection}-PostgreSql\")]");
        }

        sb.AppendLine($"public sealed class {concreteName}_PostgreSql : {baseName}, Xunit.IClassFixture<global::Warp.Tests.Fixtures.PostgreSqlClassFixture>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {concreteName}_PostgreSql(global::Warp.Tests.Fixtures.PostgreSqlClassFixture fixture) : base(fixture) {{ }}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[Xunit.Trait(\"Category\", \"SqlServer\")]");
        if (collection is not null)
        {
            sb.AppendLine($"[Xunit.Collection(\"{collection}-SqlServer\")]");
        }

        sb.AppendLine($"public sealed class {concreteName}_SqlServer : {baseName}, Xunit.IClassFixture<global::Warp.Tests.Fixtures.{sqlFixture}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {concreteName}_SqlServer(global::Warp.Tests.Fixtures.{sqlFixture} fixture) : base(fixture) {{ }}");
        sb.AppendLine("}");

        spc.AddSource($"{ns.Replace('.', '_')}_{concreteName}.g.cs", sb.ToString());
    }

    private sealed class Target(string @namespace, string baseName, bool withPush, string? collection)
    {
        public string Namespace { get; } = @namespace;

        public string BaseName { get; } = baseName;

        public bool WithPush { get; } = withPush;

        public string? Collection { get; } = collection;

        public override int GetHashCode() => (Namespace, BaseName, WithPush, Collection).GetHashCode();

        public override bool Equals(object? obj) =>
            obj is Target other
            && string.Equals(Namespace, other.Namespace, System.StringComparison.Ordinal)
            && string.Equals(BaseName, other.BaseName, System.StringComparison.Ordinal)
            && WithPush == other.WithPush
            && string.Equals(Collection, other.Collection, System.StringComparison.Ordinal);

        public void Deconstruct(out string ns, out string bn, out bool wp, out string? col)
        {
            ns = Namespace;
            bn = BaseName;
            wp = WithPush;
            col = Collection;
        }
    }
}
