<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Moberg.Warp.Worker</PackageId>
		<Description>Background worker service for Warp job processing</Description>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Warp.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Warp.Core\Warp.Core.csproj" />
		<ProjectReference Include="..\Warp.SourceGenerator\Warp.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
