using System.Globalization;
using Warp.Core.Metrics;
using static Warp.Core.Metrics.WarpMetricCatalog;

namespace Warp.Metrics.Prometheus;

/// <summary>
/// An <see cref="IMetricSource"/> that reads Warp's own metrics back from Prometheus — the TSDB Warp exported to
/// via OTel. It owns the translation from a logical <see cref="MetricRef"/> (a <see cref="WarpMetricCatalog"/> name
/// + tags) to a Prometheus metric name + label matchers and the PromQL for each seam operation, independently of the
/// local colon-key backend (no shared mapping table). Read-side only; the queries are always generated by Warp from
/// its own known metrics — never user-authored.
/// </summary>
internal sealed class PrometheusMetricSource : IMetricSource
{
    private readonly IPrometheusQueryApi _api;
    private readonly TimeSpan _defaultLookback;

    public PrometheusMetricSource(IPrometheusQueryApi api, PrometheusMetricSourceOptions options)
    {
        _api = api;
        _defaultLookback = options.DefaultLookback;
    }

    public async Task<long> GetTotalAsync(MetricRef metric, MetricWindow? window, CancellationToken ct)
    {
        var expr = $"sum({RangeOrInstant(metric, window)})";
        var result = await QueryAsync(expr, window, ct);

        return (long)Math.Round(result.Count == 0 ? 0 : PromValue.Scalar(result[0]) ?? 0);
    }

    public async Task<IReadOnlyList<SeriesBucket>> GetSeriesAsync(SeriesQuery query, CancellationToken ct)
    {
        var (from, to) = ClampRange(query.Window);
        var step = StepFor(query.Resolution);
        var by = query.BreakdownBy is { } b ? $"sum by ({b}) " : "sum ";
        var expr = $"{by}(increase({Selector(query.Metric, sum: true)}[{step}]))";

        var response = await _api.QueryRangeAsync(expr, Unix(from), Unix(to), step, ct);
        var buckets = new List<SeriesBucket>();

        foreach (var result in Results(response))
        {
            var tagValue = query.BreakdownBy is { } tag ? result.Metric.GetValueOrDefault(tag, string.Empty) : null;
            foreach (var pair in result.Values ?? [])
            {
                if (pair is { Length: 2 } && PromValue.Parse(pair[1]) is { } value)
                {
                    buckets.Add(new SeriesBucket(PromValue.BucketTime(pair[0]), tagValue, (long)Math.Round(value)));
                }
            }
        }

        return buckets;
    }

    public async Task<double> GetPercentileAsync(MetricRef metric, int percentile, MetricWindow window, CancellationToken ct)
    {
        var rows = await GetPercentileBreakdownAsync(metric, percentile, [], window, ct);

        return rows.Count == 0 ? 0 : rows[0].Value;
    }

    public async Task<double?> GetGaugeAsync(MetricRef metric, CancellationToken ct)
    {
        var response = await _api.QueryAsync(Selector(metric, sum: false), null, ct);
        var result = Results(response);

        return result.Count == 0 ? null : PromValue.Scalar(result[0]);
    }

    public async Task<IReadOnlyList<BreakdownRow>> GetBreakdownAsync(MetricRef metric, IReadOnlyList<string> groupBy, MetricWindow? window, CancellationToken ct)
    {
        var by = groupBy.Count == 0 ? string.Empty : $" by ({string.Join(", ", groupBy)}) ";
        var expr = $"sum{by}({RangeOrInstant(metric, window)})";
        var result = await QueryAsync(expr, window, ct);

        return
        [
            .. result.Select(r => new BreakdownRow(
                groupBy.ToDictionary(g => g, g => r.Metric.GetValueOrDefault(g, string.Empty), StringComparer.Ordinal),
                (long)Math.Round(PromValue.Scalar(r) ?? 0))),
        ];
    }

    public async Task<IReadOnlyList<PercentileRow>> GetPercentileBreakdownAsync(MetricRef metric, int percentile, IReadOnlyList<string> groupBy, MetricWindow? window, CancellationToken ct)
    {
        var name = PromName(metric.Name);
        var byLe = string.Join(", ", groupBy.Append("le"));
        var labels = Labels(metric.Tags);
        var bucketExpr = window is { } w
            ? $"increase({name}_bucket{labels}[{DurationLiteral(w)}])"
            : $"{name}_bucket{labels}";
        var quantile = (Math.Clamp(percentile, 0, 100) / 100.0).ToString(CultureInfo.InvariantCulture);
        var expr = $"histogram_quantile({quantile}, sum by ({byLe}) ({bucketExpr}))";

        var result = await QueryAsync(expr, window, ct);

        return
        [
            .. result.Select(r => new PercentileRow(
                groupBy.ToDictionary(g => g, g => r.Metric.GetValueOrDefault(g, string.Empty), StringComparer.Ordinal),
                PromValue.Scalar(r) ?? 0)),
        ];
    }

    public async Task<IReadOnlyList<string>> GetTagValuesAsync(MetricRef metric, string tag, MetricWindow? window, CancellationToken ct)
    {
        var expr = $"count by ({tag}) ({Selector(metric, sum: false)})";
        var result = await QueryAsync(expr, window, ct);

        return
        [
            .. result
                .Select(r => r.Metric.GetValueOrDefault(tag, string.Empty))
                .Where(v => v.Length > 0)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(v => v, StringComparer.Ordinal),
        ];
    }

    // ---- PromQL translation (per family) ---------------------------------------------------------------------

    // The Prometheus metric name for a logical metric (OTel export naming: dots→underscores, counters carry the
    // _total suffix, the ms-unit histogram carries the _milliseconds unit suffix + _bucket/_sum/_count families).
    private static string PromName(string metricName) => metricName switch
    {
        Names.AdapterCalls => "warp_adapter_calls_total",
        Names.AdapterDuration => "warp_adapter_duration_milliseconds",
        Names.EndpointCalls => "warp_endpoint_calls_total",
        Names.EndpointDuration => "warp_endpoint_duration_milliseconds",
        _ => throw new NotSupportedException($"PrometheusMetricSource has no translation for logical metric '{metricName}' yet."),
    };

    private static bool IsHistogram(string metricName) => metricName switch
    {
        Names.AdapterDuration or Names.EndpointDuration => true,
        Names.AdapterCalls or Names.EndpointCalls => false,
        _ => throw new NotSupportedException($"PrometheusMetricSource has no translation for logical metric '{metricName}' yet."),
    };

    // The scalar selector for a metric: a histogram's summed total uses the _sum family, a counter uses its name.
    private static string Selector(MetricRef metric, bool sum)
    {
        var name = PromName(metric.Name);
        var suffix = sum && IsHistogram(metric.Name) ? "_sum" : string.Empty;

        return $"{name}{suffix}{Labels(metric.Tags)}";
    }

    // A windowed read wraps the selector in increase() over the window; a lifetime read uses the raw (cumulative)
    // selector evaluated at the instant.
    private string RangeOrInstant(MetricRef metric, MetricWindow? window)
    {
        var selector = Selector(metric, sum: true);

        return window is { } w ? $"increase({selector}[{DurationLiteral(w)}])" : selector;
    }

    private Task<IReadOnlyList<PromResult>> QueryAsync(string expr, MetricWindow? window, CancellationToken ct)
        => QueryInstantAsync(expr, InstantTime(window), ct);

    // The instant a windowed read evaluates at: the window's end, clamped to now for an open-ended read; a
    // lifetime read (no window) evaluates at Prometheus's default (now).
    private static double? InstantTime(MetricWindow? window)
    {
        if (window is not { } w)
        {
            return null;
        }

        var at = w.ToUtc == DateTime.MaxValue ? DateTime.UtcNow : w.ToUtc;

        return Unix(at);
    }

    private async Task<IReadOnlyList<PromResult>> QueryInstantAsync(string expr, double? timeUnixSeconds, CancellationToken ct)
        => Results(await _api.QueryAsync(expr, timeUnixSeconds, ct));

    private static List<PromResult> Results(PromResponse response)
        => string.Equals(response.Status, "success", StringComparison.Ordinal) && response.Data is { } data ? data.Result : [];

    private static string Labels(IReadOnlyDictionary<string, string>? tags)
    {
        if (tags is null || tags.Count == 0)
        {
            return string.Empty;
        }

        var matchers = tags
            .OrderBy(t => t.Key, StringComparer.Ordinal)
            .Select(t => $"{t.Key}=\"{Escape(t.Value)}\"");

        return $"{{{string.Join(",", matchers)}}}";
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);

    // A PromQL range-vector duration literal for the window's span (seconds), floored to 1s.
    private string DurationLiteral(MetricWindow window)
    {
        var (from, to) = ClampRange(window);
        var seconds = Math.Max(1, (long)(to - from).TotalSeconds);

        return $"{seconds}s";
    }

    // Bounds an open-ended window (MinValue/MaxValue from an "all history" read) to a sane range Prometheus can
    // evaluate: end at now, start no earlier than the configured lookback.
    private (DateTime From, DateTime To) ClampRange(MetricWindow window)
    {
        var now = DateTime.UtcNow;
        var to = window.ToUtc == DateTime.MaxValue || window.ToUtc > now ? now : DateTime.SpecifyKind(window.ToUtc, DateTimeKind.Utc);
        var floor = now - _defaultLookback;
        var from = window.FromUtc == DateTime.MinValue || window.FromUtc < floor ? floor : DateTime.SpecifyKind(window.FromUtc, DateTimeKind.Utc);

        return (from, to < from ? from : to);
    }

    private static string StepFor(MetricResolution resolution) => resolution switch
    {
        MetricResolution.Fine => "300s",
        MetricResolution.Hourly => "1h",
        _ => "1d",
    };

    private static double Unix(DateTime dt)
        => (DateTime.SpecifyKind(dt, DateTimeKind.Utc) - DateTime.UnixEpoch).TotalSeconds;
}
