using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Warp.Http.SourceGenerator.Emitters;

internal static class RegistryEmitter
{
    public static string Emit(string assemblySafeIdentifier, IReadOnlyList<(HttpEndpointModel Model, BindingPlan Plan)> endpoints)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("namespace Warp.Http.Generated");
        sb.AppendLine("{");

        for (var i = 0; i < endpoints.Count; i++)
        {
            DelegateEmitter.Emit(sb, endpoints[i].Model, endpoints[i].Plan, i);
        }

        sb.Append("    internal static class WarpHttpModuleInit_").AppendLine(assemblySafeIdentifier);
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Register()");
        sb.AppendLine("        {");
        for (var i = 0; i < endpoints.Count; i++)
        {
            EmitRegistryAdd(sb, endpoints[i].Model, i);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitRegistryAdd(StringBuilder sb, HttpEndpointModel ep, int index)
    {
        var handlerFqn = ep.HandlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var requestFqn = ep.RequestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var responseFqn = ep.ResponseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var kind = ep.Kind == HttpHandlerKind.Stream
            ? "global::Warp.Http.Discovery.HandlerKind.Stream"
            : "global::Warp.Http.Discovery.HandlerKind.Request";

        sb.AppendLine("            global::Warp.Http.Discovery.WarpGeneratedHttpRegistry.Add(new global::Warp.Http.Discovery.HttpEndpointDescriptor");
        sb.AppendLine("            {");
        sb.Append("                Method = \"").Append(EscapeStringLiteral(ep.Method)).AppendLine("\",");
        sb.Append("                Route = \"").Append(EscapeStringLiteral(ep.Route)).AppendLine("\",");
        sb.Append("                Group = ").Append(StringLiteralOrNull(ep.Group)).AppendLine(",");
        sb.Append("                Name = ").Append(StringLiteralOrNull(ep.Name)).AppendLine(",");
        sb.Append("                HandlerType = typeof(").Append(handlerFqn).AppendLine("),");
        sb.Append("                RequestType = typeof(").Append(requestFqn).AppendLine("),");
        sb.Append("                ResponseType = typeof(").Append(responseFqn).AppendLine("),");
        sb.Append("                Kind = ").Append(kind).AppendLine(",");
        sb.Append("                HandlerDelegate = WarpHttpDelegate_").Append(index).AppendLine(".Handler,");
        if (ep.RequiresFormBinding)
        {
            sb.AppendLine("                RequiresFormBinding = true,");
        }

        sb.AppendLine("            });");
        sb.AppendLine();
    }

    private static string StringLiteralOrNull(string? value)
        => value is null ? "null" : "\"" + EscapeStringLiteral(value) + "\"";

    private static string EscapeStringLiteral(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
